name: send-slack-message

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: test
          slack-text: |
            ${{ github.repository }} build done
            https://github.com/louiscklaw/lichee-nano/commit/$GITHUB_SHA/checks

      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
