github-actions-checkout-orphan-branch-tryout:
  runs-on: ubuntu-latest
  steps:


    - uses: actions/checkout@v2
      with:
        ref: test_orphan_branch
        path: 'test_orphan_branch'

    - uses: actions/checkout@v2
      with:
        ref: master
        path: 'master'

    - name: github-actions-checkout-orphan-branch-tryou
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo 'helloworld'
        ls -l .
        ls -l ..
        ls -l test_orphan_branch

        cd test_orphan_branch
          touch hello_orphan_branch
          git add hello_orphan_branch
          git commit -m"test commit using command line,"
        cd ..
