github-actions-checkout-orphan-branch-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        ref: test_orphan_branch
        path: '/tmp'

    - name: github-actions-checkout-orphan-branch-tryou
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo 'helloworld'