github-actions-checkout-orphan-branch-tryout:
  runs-on: ubuntu-latest
  steps:

    # NOTES: actions/checkout will clear every and then checkout, so must define path for each branch

    - uses: actions/checkout@v2
      with:
        ref: master
        path: 'master'
    - uses: actions/checkout@v2
      with:
        ref: test_orphan_branch
        path: 'master/test_orphan_branch'

    - name: github-actions-checkout-orphan-branch-tryou
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo 'helloworld'
        ls -l .
        ls -l ..
        ls -l master/test_orphan_branch

        cd master/test_orphan_branch
          touch hello_orphan_branch
          git config --global user.email "louiscklaw@github.com"
          git config --global user.name "louiscklaw"

          git add hello_orphan_branch
          git commit -m"test commit using command line,"
          git push
        cd ..
