github-actions-checkout-orphan-branch-tryout:
  runs-on: ubuntu-latest
  steps:
    - name: github-actions-helloworld-tryout
      uses: actions/checkout@v2

    - name: github-actions-checkout-orphan-branch-tryou
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo 'helloworld'
        node --version
        npm -v
        yarn -v
