# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: build matrix
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting

    runs-on: ubuntu-latest
    steps:

      - name: Hello world
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          who-to-greet: 'Mona the Octocat'

      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
