github_actions_docker_container:
  runs-on: ubuntu-latest
  container: node:10.16-jessie
  steps:
    - uses: actions/checkout@v2
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        echo 'helloworld'
        hostname
        node -v
