github_actions_docker_container:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2

  - name: github-actions-helloworld-tryout
    env: # Or as an environment variable
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    run: |
      echo 'helloworld'
