github-actions-orphan-tryout:
  runs-on: ubuntu-latest
  steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: github-actions-orphan-tryout/test_dir
