github-actions-orphan-tryout:
  runs-on: ubuntu-latest
  steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: hello-orphan
        publish_dir: ./github-actions-orphan-tryout/test_dir/test_orphan_file.txt
        allow_empty_commit: true
        keep_files: false
        force_orphan: true
        exclude_assets: '.github,exclude-file1,exclude-file2'