github-actions-orphan-tryout:
  runs-on: ubuntu-latest
  steps:
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: github-actions-orphan-tryout/out # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
