github_actions_add_and_commit_tryout:
  runs-on: ubuntu-latest
  steps:
    - name: run test
      env:
        LOUISCKLAW_GITHUB_TOKEN: ${{ secrets.LOUISCKLAW_GITHUB_TOKEN }}

      run: |
        git config --global user.email "louiscklaw@gmail.com"
        git config --global user.name "louiscklaw"
        git clone https://louiscklaw:$LOUISCKLAW_GITHUB_TOKEN@github.com/louiscklaw/github-playlist.git --branch=master QA_test_result
        echo 2 > QA_test_result/helloworld.txt
        ls -l QA_test_result
        cd QA_test_result
          git add .
          git commit -m"a for apple,"
          git push
