github_actions_add_and_commit_tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        repository: 'LynkedKK/QA_test_result'
        path: "result_placeholder"

    - name: run test
      run: |
        touch result_placeholder/helloworld.txt

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: louiscklaw
        author_email: louiscklaw@gmail.com
        message: "update routine result"
        cwd: "result_placeholder"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
