github_actions_add_and_commit_tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        repository: 'LynkedKK/QA_test_result'
        path: "QA_test_result"

    - name: run test
      run: |
        echo 1 > QA_test_result/helloworld.txt
        ls -l QA_test_result

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: louiscklaw
        author_email: louiscklaw@gmail.com
        message: "update routine result"
        cwd: "QA_test_result"
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
