# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: build matrix
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Greeting
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest, macos-latest, windows-latest]
        node: [6, 8, 10, 12]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo the greeting's time
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: simple print node version
        run: node --version
