# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://github.com/sdras/awesome-actions

github-firebase-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - run: |
        echo 'helloworld'
        node --version
        npm -v
        yarn -v
        yarn add global firebase-tools firebase-functions firebase-admin
        firebase --help

      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
