
build-linux:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2

  - run: |
      sudo apt-get install libxml2-utils   \
                            icnsutils       \
                            graphicsmagick  \
                            xz-utils        \
                            build-essential \
                            libudev-dev



# build-macos:
#   runs-on: macos-latest

#   steps:
#   - uses: actions/checkout@v2
#   - uses: actions/setup-node@v1
#     with:
#       node-version: ${{ env.NODE_VERSION }}
#   - uses: olegtarasov/get-tag@v2
#     id: tag_name
#   - run: npm install
#   - run: npm run test-build
#     if: ${{ !steps.tag_name.outputs.tag }}
#   - run: npm run release
#     if: ${{ steps.tag_name.outputs.tag }}
#     env:
#       GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#       CSC_KEY_PASSWORD: "${{ secrets.CSC_KEY_PASSWORD }}"
#       CSC_LINK: "${{ secrets.CSC_LINK }}"

# build-windows:
#   runs-on: windows-latest

#   steps:
#   - uses: actions/checkout@v2
#   - uses: actions/setup-node@v1
#     with:
#       node-version: ${{ env.NODE_VERSION }}
#   - uses: olegtarasov/get-tag@v2
#     id: tag_name
#   - run: npm install
#   - run: npm run test-build
#     if: ${{ !steps.tag_name.outputs.tag }}
#   - run: npm run release
#     if: ${{ steps.tag_name.outputs.tag }}
#     env:
#       GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
