# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://github.com/sdras/awesome-actions

github-actions-firebase-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - run: |
        cd github-actions-firebase-tryout
          curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
          chmod +x ./firebase_bin
          ./firebase_bin --help

          echo 'helloworld'
          node --version
          npm -v
          yarn -v
          ./firebase_bin --help
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}