# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://github.com/sdras/awesome-actions

github-actions-firebase-tryout:
  runs-on: ubuntu-latest
  steps:
    - name: github-actions-helloworld-tryout
      uses: actions/checkout@v2

    - name: github-actions-firebase-tryout
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn add global firebase-tools firebase-functions firebase-admin
        cd github-actions-firebase-tryout
          echo 'helloworld'
          node --version
          npm -v
          yarn -v
