# https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
action_secrets_tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: action-secrets-tryout
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        echo 'helloworld'
        node --version
        npm -v
        yarn -v
