# https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
action_secrets_tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: action-secrets-tryout
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
        INPUT_TEST_JSON: my_secret.json
        OUTPUT_TEST_JSON: $HOME/secrets/my_secret.json

      run: |
        cd action-secrets-tryout
          ./decrypt_secret.sh
        cd ..
    - name: test-cat
      run: |
        cd action-secrets-tryout
          cat $HOME/secrets/my_secret.json
        cd ..
    - name: test-diff
      run: |
        cd action-secrets-tryout
          diff $INPUT_TEST_JSON $OUTPUT_TEST_JSON
        cd ..
