# https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
action_secrets_tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: action-secrets-tryout
      run: ./action-secrets-tryout/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    - name: Test printing your secret (Remove this step in production)
      run: |
        cd action-secrets-tryout
          cat $HOME/secrets/my_secret.json
        cd ..