name: merge

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Install project dependencies
      run: |
        cd github-actions-merge
        pip install -r requirements.txt

    - name: run test
      run: |
        cd github-actions-merge
        python3 merge.py

    - name: Send message to Slack API
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: test
        slack-text: |
          ${{ github.repository }} build done
          https://github.com/louiscklaw/lichee-nano/commit/$GITHUB_SHA/checks

    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
