# https://medium.com/@sandeepqaops/setting-up-github-actions-for-react-native-mobile-app-for-ios-simulator-with-appium-96890c7bb303
# Pre-Commit E2E Tests in iOS
name: ios-emulator-test-14
# Controls when the action will run.
on:
  push:
    branches:
      - test/appium-on-mac-tryout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Repo and Dependencies
        run: |
          cd github-actions-ios-emulator-tryout
            npm install --save-dev
            npm install appium-doctor
            ./node_modules/.bin/appium-doctor
          cd -

          brew install ffmpeg
