on:
  push:
    branches:
      - test/ios12-runtime-install/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Install iOS 12.4 Runtime
        run: |
          gem install xcode-install
          xcversion simulators --install='iOS 12.4'
