name: master_build
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: do-something

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
        run: |
          echo 'helloworld'