name: poc
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: merge branch
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      run: |
        sudo cat /etc/sudoers
        sudo ls -l /etc/sudoers.d
        sudo cat /etc/sudoers.d/runner
