name: poc
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: poc greeting
    runs-on: ubuntu-latest
    steps:

      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello

      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
