name: master_build
on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2.2.0
      with:
        api-level: 29
        script: sh ./github-android-emulator-tryout/scripts.sh