name: test_upload_artifact
on: [push]

jobs:
  action_upload_artifact_tryout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: action-upload-artifact-tryout
        uses: actions/upload-artifact@v2
        with:
          name: 'upload-artifact-tryout'
          path: action-upload-artifact-tryout/helloworld
